version: '2'
volumes:
    config:
    pihole_config:
    dnsmasq_config:
    dnscrypt_config:
services:
  homeassistant:
    build: homeassistant
    ports:
      - 8081:8123
    privileged: true
    volumes:
      - 'config:/config'
    restart: always
    devices:
      - '/dev:/dev'
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - '1883:1883'
    restart: always
  hass-configurator:
    image: 'causticlab/hass-configurator-docker:arm'
    restart: always
    ports:
      - '8080:3218'
    volumes:
      - 'config:/hass-config'
    environment:
      - HC_BASEPATH=/hass-config
  node-red:
    image: 'nodered/node-red:latest'
    environment:
      - TZ=Americas/Phoenix
    ports:
      - '1880:1880'
    volumes:
      - 'config:/node-red-data'
    restart: always
  pihole:
    build: ./pihole
    privileged: true
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    dns:
      - '127.0.0.1'
      - '1.1.1.2'
    network_mode: host
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '80:80/tcp'
      - '443:443/tcp'

  # set pihole DNS1 and DNS2 service variables to 127.0.0.1#5053 to use dnscrypt-proxy for upstream DNS
  dnscrypt-proxy:
    build: ./dnscrypt-proxy
    volumes:
      - 'dnscrypt_config:/config'
    ports:
      - '5053:5053/udp'